export const defaultDegrees = [
  "Bachelor of Science",
  "Bachelor of Arts",
  "Bachelor of Engineering",
  "Bachelor of Commerce",
  "Master of Science",
  "Master of Arts",
  "Master of Business Administration",
  "Master of Engineering",
  "Doctor of Philosophy",
  "Doctor of Medicine",
  "Associate Degree",
  "High School Diploma",
];

export const defaultFields = [
  "Computer Science",
  "Engineering",
  "Business Administration",
  "Psychology",
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Economics",
  "Political Science",
  "History",
  "English Literature",
  "Medicine",
  "Law",
  "Architecture",
  "Design",
  "Marketing",
  "Finance",
  "Accounting",
  "Nursing",
];
